### ISSUE TITLE
No SEO tab, error when trying to uninstall module

### ISSUE THREAD

**Issue by tyssen** [NicoKnoll/MarkupSEO#10]
I'm not getting an SEO tab appear on my publish/edit pages (I have specified templates to get the tab in the module's settings). So I thought I should maybe uninstall and reinstall, but when I try to uninstall I get:
 
> Recoverable Fatal Error: Argument 1 passed to Fields::___delete() must implement interface Saveable, null given (line 265 of /wire/core/Fields.php)

Or are there some other set-up steps I've missed?

**Comment by JoZ3** [comment]
same error here... PW version 2.5.3

**Comment by NicoKnoll** [comment]
what fixed it for tyssen: if you can't delete it go to fields and delete all of the (remaining) seo fields manually. Then go to the modules code and delete the whole ___delete() function. Then uninstall the module and delete the .module file. Then download the most recent version (0.8.1), install it and let me now if it works better afterwards

**Comment by JoZ3** [comment]
@NicoKnoll thanks, now work!!!!
