### ISSUE TITLE
switching templates - error!

### ISSUE THREAD

**Issue by tbba** [NicoKnoll/MarkupSEO#12]
Hi Nico, when changing a template for a page, I get this sometimes:
Notice: Trying to get property of non-object in /.../site/modules/MarkupSEO/MarkupSEO.module on line 101

(The old template *was* in the list of templates in the SEO module settings, the new template *not*)

**Comment by tbba** [comment]
same error if I change the name (slug) of a page

**Comment by NicoKnoll** [comment]
should be fixed
