### ISSUE TITLE
Trying to autofill seo image field

### ISSUE THREAD

**Issue by mike131** [NicoKnoll/MarkupSEO#13]
Hi,

I am trying to autofill the Image field on the SEO tab based on the image uploaded into the content tab.

I tried var_dumping the $event to see if I could extract the data (image) from there but i am unable to find it.

Does this seem like something that is even possible?

**Comment by NicoKnoll** [comment]
Normally auto fill only works if you choose an image field for it. But of course you can customize the module to your needs. I'll post an example shortly :)

**Comment by NicoKnoll** [comment]
Add this to  hookCustomizeSeoTab:

// get body content from field
		$bodyContent = $e->return->get('body')->value;
		
		// get image
		preg_match('%<img.*src=\"(.*)\"%Uis', $bodyContent, $match);
		$bodyContentImage = $match[1];
		
		// populate sep field with image url
		$e->return->get('seo_image')->value = $bodyContentImage;
