### ISSUE TITLE
Facebook Open Graph requires meta property tag

### ISSUE THREAD

**Issue by mauricius** [nicoknoll/MarkupSEO#18]
As stated in https://developers.facebook.com/docs/sharing/webmasters#markup, the Facebook Open Graph requires meta tags with **property** attribute instead of **name**.

I solved the problem adding a simple check when rendering the module in order to output the correct markup in case of _og:_ tags.

**Comment by jasonhuck** [comment]
You can verify this with Facebook's Sharing Debugger. Enter a URL and it will claim the open graph tags are missing. Easy to overlook because sites will often infer the correct values based on other available information. 

https://developers.facebook.com/tools/debug/sharing/

**Comment by mauricius** [comment]
Fixed with https://github.com/nicoknoll/MarkupSEO/commit/37cc2cc28903f869965b724d17c6b7f44a89702e
