### ISSUE TITLE
MarkupSEO  in combination with  ProCache removes metatags

### ISSUE THREAD

**Issue by AlfredBes** [NicoKnoll/MarkupSEO#25]
Hello Nico,

First of all, thank you for this great module. Very helpfull and handy.

Maybe you allready read this issue on the ProCache forum but I'll inform you anyway.
When using MarkupSEO in combination with ProCache the meta tags are removed.
Ryan suggested a solution that works.
https://processwire.com/talk/topic/11835-procache-with-markupseo-removes-all-meta-tags/

Alfred

**Comment by Notanotherdotcom** [comment]
Yep, definitely works, and in case you don't have access to the ProCache forum Nico, the solution is as simple as this:

> Alfred, grimezy, I've taken a closer look at the MarkupSEO module and believe the issue is what it's hooking into:
> `$this->addHookAfter("ProcessPageView::execute", $this, 'hookMethodAuto');`
> It should instead be looking into "Page::render". If you update that line to this, I think that should fix it:
> `$this->addHookAfter("Page::render", $this, 'hookMethodAuto');`

**Comment by NicoKnoll** [comment]
I should rebuy access someday :)
