### ISSUE TITLE
Make the automatic insertion of <title> optional

### ISSUE THREAD

**Issue by mike-anthony** [NicoKnoll/MarkupSEO#7]
Refer: [#99, MarkupSEO](https://processwire.com/talk/topic/8007-markupseo-the-all-in-one-seo-solution-for-processwire/?p=85834)

In order to ensure that the `<title>` and `og:title` differ, I should be able to use my own `<title>` tags.

**Comment by NicoKnoll** [comment]
It is optional. If you leave the "titleFormat" empty it doesn't get included (Y)
