### ISSUE TITLE
title tag with source from individual field

### ISSUE THREAD

**Issue by tbba** [NicoKnoll/MarkupSEO#9]
I tried to use my own field (title_window, string field) as source for the title tag:

{title_window} - {sitename}

That does not work, what I get is this:

<title>{title_window} | MyCompany</title>

Is this intended?

**Comment by NicoKnoll** [comment]
Yeah. 'cause at the moment the only tags working are {title} and {sitename}. It's hard coded. Maybe I will extend that in the future.
